// =============================================================================
//  Jenkins Pipeline: "cool-webserver"
//
//  1. Generates a small but slick static website (HTML/CSS/JS/SVG + build info)
//  2. Generates an nginx web-server config (gzip, security headers, /health)
//  3. EXPORTS EVERYTHING into ONE self-contained Dockerfile (content is embedded
//     via Dockerfile heredocs, so the Dockerfile alone can rebuild the server)
//  4. Builds the image from an EMPTY context (proves nothing else is needed)
//  5. Runs it, smoke-tests it, and archives the Dockerfile as a build artifact
//
//  Agent requirements: Linux, Docker CLI + daemon with BuildKit (Docker 23+).
// =============================================================================

pipeline {
    agent any

    options {
        buildDiscarder(logRotator(numToKeepStr: '10'))
        disableConcurrentBuilds()
        timeout(time: 15, unit: 'MINUTES')
    }

    parameters {
        string(name: 'SITE_TITLE',   defaultValue: 'Shipped by Jenkins', description: 'Headline shown on the site')
        string(name: 'IMAGE_NAME',   defaultValue: 'cool-webserver',     description: 'Docker image name')
        string(name: 'HOST_PORT',    defaultValue: '8180',               description: 'Host port to publish the web server on')
        booleanParam(name: 'KEEP_RUNNING', defaultValue: true, description: 'Leave the web server running after the build')
    }

    environment {
        CONTAINER_NAME  = 'cool-webserver'
        DOCKER_BUILDKIT = '1'
    }

    stages {

        stage('Prepare workspace') {
            steps {
                sh 'rm -rf site server export && mkdir -p site server export'
            }
        }

        stage('Generate content') {
            steps {
                sh '''
cat > site/index.html <<'__HTML__'
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Shipped by Jenkins</title>
  <link rel="icon" href="favicon.svg" type="image/svg+xml">
  <link rel="stylesheet" href="styles.css">
</head>
<body>
  <main class="dock">
    <section class="copy">
      <h1 id="title">Shipped by Jenkins</h1>
      <p class="lede">This page, the nginx server delivering it and its configuration were all
        generated by a Jenkins pipeline, then packed into a single self&#8209;contained Dockerfile.</p>
      <dl class="facts">
        <div><dt>Build</dt><dd id="build">local</dd></div>
        <div><dt>Job</dt><dd id="job">&ndash;</dd></div>
        <div><dt>Built</dt><dd id="built">&ndash;</dd></div>
        <div><dt>Commit</dt><dd id="commit">&ndash;</dd></div>
      </dl>
      <button id="restack" type="button">Stack them again</button>
    </section>

    <section class="yard" aria-label="Pipeline stages, stacked as shipping containers">
      <ol class="stack go" id="stack">
        <li class="box c1"><span>Generate content</span></li>
        <li class="box c2"><span>Configure nginx</span></li>
        <li class="box c3"><span>Export Dockerfile</span></li>
        <li class="box c4"><span>Build image</span></li>
        <li class="box c5"><span>Smoke test</span></li>
        <li class="box c6"><span>Live on port 80</span></li>
      </ol>
    </section>
  </main>

  <svg class="water" viewBox="0 0 1440 120" preserveAspectRatio="none" aria-hidden="true">
    <path d="M0 60 C 180 20 360 100 540 60 S 900 20 1080 60 S 1300 100 1440 60 V120 H0 Z"/>
  </svg>
  <script src="app.js"></script>
</body>
</html>
__HTML__

cat > site/styles.css <<'__CSS__'
:root {
  --dusk-top: #22365e;
  --dusk-low: #13213d;
  --fog: #eef1f4;
  --fog-dim: #a9b4c6;
  --signal: #e8b923;
  --rust: #b8442c;
  --teal: #2a7f8f;
  --steel: #4a6fa5;
  --bone: #d9d4c7;
  --display: "Avenir Next", Futura, "Century Gothic", "Trebuchet MS", sans-serif;
  --narrow: "Avenir Next Condensed", "Roboto Condensed", "Arial Narrow", sans-serif;
}
* { box-sizing: border-box; margin: 0; padding: 0; }
html, body { min-height: 100%; }
body {
  background: linear-gradient(180deg, var(--dusk-top) 0%, var(--dusk-low) 70%);
  color: var(--fog);
  font-family: var(--display);
  overflow-x: hidden;
}
.dock {
  max-width: 1120px;
  margin: 0 auto;
  padding: 10vh 28px 180px;
  display: grid;
  gap: 56px;
  align-items: end;
}
@media (min-width: 860px) { .dock { grid-template-columns: 1fr 1fr; } }

h1 {
  font-size: clamp(2.8rem, 7vw, 5.4rem);
  line-height: 0.95;
  font-weight: 800;
  letter-spacing: -0.035em;
  max-width: 10ch;
}
.lede {
  margin-top: 24px;
  max-width: 44ch;
  font-size: 1.125rem;
  line-height: 1.6;
  color: var(--fog-dim);
}
.facts {
  margin-top: 36px;
  display: grid;
  grid-template-columns: repeat(2, minmax(0, 1fr));
  gap: 18px 32px;
  max-width: 440px;
}
.facts dt { font-size: 0.85rem; color: var(--fog-dim); }
.facts dd { margin-top: 2px; font-size: 1.05rem; font-weight: 600; overflow-wrap: anywhere; }

button {
  margin-top: 40px;
  font: 700 1rem var(--display);
  color: var(--dusk-low);
  background: var(--signal);
  border: 0;
  border-radius: 4px;
  padding: 14px 24px;
  cursor: pointer;
}
button:hover { background: #f3cb45; }
button:focus-visible { outline: 3px solid var(--fog); outline-offset: 3px; }

/* The container yard: pipeline stages drop in as shipping containers */
.yard {
  border-bottom: 8px solid #5b6b82;
  padding: 0 8px;
  min-height: 420px;
  display: flex;
  align-items: flex-end;
  justify-content: center;
}
.stack {
  list-style: none;
  width: 100%;
  max-width: 460px;
  display: flex;
  flex-direction: column-reverse;
  gap: 4px;
}
.box {
  position: relative;
  height: 58px;
  border-radius: 2px;
  display: flex;
  align-items: center;
  padding-left: 18px;
  font: 700 1.05rem var(--narrow);
  letter-spacing: 0.02em;
  color: var(--fog);
  background-image: repeating-linear-gradient(90deg, rgba(0,0,0,0.16) 0 3px, transparent 3px 11px);
  box-shadow: inset 0 -4px 0 rgba(0,0,0,0.22), inset 0 4px 0 rgba(255,255,255,0.08);
}
.box::after {
  content: "";
  position: absolute;
  right: 14px; top: 8px; bottom: 8px;
  width: 18px;
  border-left: 3px solid rgba(0,0,0,0.28);
  border-right: 3px solid rgba(0,0,0,0.28);
}
.c1 { background-color: var(--rust);   margin-right: 8%; }
.c2 { background-color: var(--signal); color: var(--dusk-low); margin-left: 6%; }
.c3 { background-color: var(--teal);   margin-right: 2%; }
.c4 { background-color: var(--steel); margin-left: 10%; }
.c5 { background-color: var(--bone);   color: var(--dusk-low); margin-right: 12%; }
.c6 { background-color: #8f3b2a;       margin-left: 4%; }

.stack.go .box { animation: drop 0.7s cubic-bezier(0.3, 1.35, 0.5, 1) both; }
.stack.go .c1 { animation-delay: 0.20s; }
.stack.go .c2 { animation-delay: 0.65s; }
.stack.go .c3 { animation-delay: 1.10s; }
.stack.go .c4 { animation-delay: 1.55s; }
.stack.go .c5 { animation-delay: 2.00s; }
.stack.go .c6 { animation-delay: 2.45s; }
@keyframes drop {
  from { transform: translateY(-110vh); }
  to   { transform: none; }
}

.water { position: fixed; left: 0; bottom: 0; width: 100%; height: 110px; fill: #0e1a31; opacity: 0.9; }

@media (prefers-reduced-motion: reduce) {
  .stack.go .box { animation: none; }
}
__CSS__

cat > site/app.js <<'__JS__'
(function () {
  var stack = document.getElementById('stack');

  document.getElementById('restack').addEventListener('click', function () {
    stack.classList.remove('go');
    void stack.offsetWidth;          // restart the CSS animation
    stack.classList.add('go');
  });

  function set(id, value) {
    if (value) document.getElementById(id).textContent = value;
  }

  fetch('build-info.json', { cache: 'no-store' })
    .then(function (r) { return r.json(); })
    .then(function (info) {
      set('title', info.title);
      if (info.title) document.title = info.title;
      set('build', '#' + info.build);
      set('job', info.job);
      set('commit', (info.commit || '').slice(0, 7) || 'none');
      var d = new Date(info.builtAt);
      if (!isNaN(d)) set('built', d.toLocaleString([], { dateStyle: 'medium', timeStyle: 'short' }));
    })
    .catch(function () { /* page still works without build info */ });
})();
__JS__

cat > site/favicon.svg <<'__SVG__'
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64">
  <rect width="64" height="64" rx="10" fill="#13213d"/>
  <rect x="10" y="38" width="44" height="12" fill="#b8442c"/>
  <rect x="14" y="24" width="36" height="12" fill="#e8b923"/>
  <rect x="18" y="10" width="28" height="12" fill="#2a7f8f"/>
</svg>
__SVG__

# Build metadata (unquoted heredoc on purpose: shell variables are expanded here)
cat > site/build-info.json <<__JSON__
{
  "title":   "${SITE_TITLE}",
  "build":   "${BUILD_NUMBER}",
  "job":     "${JOB_NAME}",
  "commit":  "\${GIT_COMMIT:-}",
  "builtAt": "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
}
__JSON__

echo "Generated site content:"
ls -la site
'''
            }
        }

        stage('Configure web server') {
            steps {
                sh '''
cat > server/default.conf <<'__NGINX__'
server {
    listen      80;
    server_name _;
    root        /usr/share/nginx/html;
    index       index.html;

    server_tokens off;
    gzip on;
    gzip_types text/css application/javascript application/json image/svg+xml;

    add_header X-Content-Type-Options "nosniff" always;
    add_header X-Frame-Options "DENY" always;
    add_header Referrer-Policy "no-referrer" always;

    location = /health {
        access_log off;
        default_type application/json;
        return 200 '{"status":"ok"}';
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
__NGINX__
cat server/default.conf
'''
            }
        }

        stage('Export everything to Dockerfile') {
            steps {
                sh '''
DF=export/Dockerfile
D=__JENKINS_EMBEDDED_EOF__
            
{
  echo '# syntax=docker/dockerfile:1'
  echo "# Generated by Jenkins job '\${JOB_NAME}' build #\${BUILD_NUMBER} at $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo '# Fully self-contained: web server, config and every content file are embedded below.'
  echo '#   Build: docker build -t cool-webserver .        (BuildKit required, Docker 23+ default)'
  echo '#   Run:   docker run -d -p 8180:80 cool-webserver'
  echo
  echo 'FROM nginx:1.27-alpine'
  echo 'LABEL org.opencontainers.image.title="cool-webserver" jenkins.build="'"\${BUILD_NUMBER}"'"'
  echo 'RUN rm -rf /usr/share/nginx/html/*'
  echo
  echo '# ---- Web server configuration ----'
  echo 'COPY <<'\'"$D"'\'' /etc/nginx/conf.d/default.conf'
  cat server/default.conf
  echo "$D"

  find site -type f | sort | while read -r f; do
    rel="\${f#site/}"
    echo
    echo "# ---- Content: \${rel} ----"
    echo 'COPY <<'\'"$D"'\'' /usr/share/nginx/html/'"\${rel}"
    cat "$f"
    echo "$D"
  done

  echo
  echo 'EXPOSE 80'
  echo 'HEALTHCHECK --interval=30s --timeout=3s --retries=3 CMD wget -qO- http://127.0.0.1/health || exit 1'
} > "$DF"

echo "=========== Exported Dockerfile ==========="
cat "$DF"
'''
            }
        }

        stage('Build image from Dockerfile only') {
            steps {
                sh '''
cd export
ls -la
docker build -t "${IMAGE_NAME}:${BUILD_NUMBER}" -t "${IMAGE_NAME}:latest" .
'''
            }
        }

        stage('Run web server') {
            steps {
                sh '''
docker rm -f "${CONTAINER_NAME}" >/dev/null 2>&1 || true
docker run -d --name "${CONTAINER_NAME}" --restart unless-stopped -p "${HOST_PORT}:80" "${IMAGE_NAME}:${BUILD_NUMBER}"
'''
            }
        }

        stage('Smoke test') {
            steps {
                sh '''
for i in $(seq 1 30); do
  if docker exec "${CONTAINER_NAME}" wget -qO- http://127.0.0.1/health 2>/dev/null | grep -q ok; then
    echo "Health check passed"
    break
  fi
  if [ "$i" -eq 30 ]; then
    echo "Web server never became healthy"
    docker logs "${CONTAINER_NAME}"
    exit 1
  fi
  sleep 1
done

docker exec "${CONTAINER_NAME}" wget -qO- http://127.0.0.1/            | grep -q 'id="stack"'
docker exec "${CONTAINER_NAME}" wget -qO- http://127.0.0.1/styles.css  | grep -q 'keyframes drop'
docker exec "${CONTAINER_NAME}" wget -qO- http://127.0.0.1/build-info.json
echo
echo "All content served correctly"
'''
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'export/Dockerfile, site/**, server/**', fingerprint: true, allowEmptyArchive: true
        }
        success {
            echo "Web server image: ${params.IMAGE_NAME}:${env.BUILD_NUMBER}"
            echo "Exported Dockerfile archived as a build artifact: export/Dockerfile"
            echo "Browse to http://<jenkins-agent-host>:${params.HOST_PORT}/"
        }
        cleanup {
            script {
                if (!params.KEEP_RUNNING || currentBuild.currentResult != 'SUCCESS') {
                    sh 'docker rm -f "${CONTAINER_NAME}" >/dev/null 2>&1 || true'
                }
            }
        }
    }
}